parameters:

    payment.event.dispatcher.class: "Mmoreram\\PaymentCoreBundle\\Services\\PaymentEventDispatcher"
    payment.currency.wrapper.class: "Mmoreram\\PaymentCoreBundle\\Services\\Wrapper\\CurrencyWrapper"