services:

    payment.currency.wrapper:
        class: Mmoreram\PaymentCoreBundle\Services\Wrapper\CurrencyWrapper
        arguments:
            payment.default.currency: %payment.default.currency%
            payment.cart.wrapper: @payment.cart.wrapper

    payment.event.dispatcher:
        class: %payment.event.dispatcher.class%
        arguments:
            event.dispatcher: @event_dispatcher