services:

    payment.currency.wrapper:
        class: %payment.currency.wrapper.class%
        arguments:
            payment.bridge: @payment.bridge

    payment.event.dispatcher:
        class: %payment.event.dispatcher.class%
        arguments:
            event.dispatcher: @event_dispatcher